config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  devise_for :customers

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:index, :show, :new, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    get "about" => "homes#about"

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy ]
    delete 'cart_items/:id' => 'cart_products#destroy', as: 'destroy_cart_item'

    resources :orders, only: [:index, :show, :create, :new] do
      collection do
        post :confirm
        get :complete
      end
    end

    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    resources :customers, only: [:show, :edit, :update] do
      member do
        get :quit_confirm
        patch :quit
      end
    end

  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy

  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true

  enum pay_type: {クレジットカード:0, 銀行振込:1}
  enum buy_status: {入金待ち:0, 入金確認:1,  製作中:2, 発送準備中:3, 発送済み:4}

  def shipping_cost
    800
  end

  def cal_price(customer)
    shipping_cost + customer.cart_items.sum(&:subtotal)
  end

  def order_item_status_auto_update
    if self.buy_status == "入金確認"
      self.order_items.each do |order_item|
        order_item.update(make_status: "製作待ち")
      end
    #デフォルトで「着手不可」にはなるが、誤って「入金確認」を押した際に製作ステータスを再度「着手不可」へ戻すために以下が必要
    elsif self.buy_status == "入金待ち"
      self.order_items.each do |order_item|
        order_item.update(make_status: "着手不可")
      end
    end
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    order.order_item_status_auto_update
    redirect_to admin_order_path(params[:id])
  end


  private


  def order_params
    params.require(:order).permit(:buy_status)
  end



end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container my-4">
  <div class="row">
    <h3 class="mt-2">注文履歴詳細</h3>
  </div>

  <div class="row">
    <div>
      <table class="table-light table table-borderless">
        <thead class="thead-light">
        <tr>
         <th>購入者</th>
         <td>
           <%= link_to admin_customer_path(@order.customer) do %>
             <%= customer_full_name(@order.customer.id) %>
           <% end %>
          </td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime('%Y/%m/%d')%></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            <%= delivery_full_address(@order.id) %></br>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.pay_type %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: [:admin,@order], local:true do |f| %>
              <%= f.select :buy_status, Order.buy_statuses.keys %>
              <%= f.submit '更新', class: "btn btn-success btn-sm" %>
            <% end %>
          </td>
        </tr>
        </thead>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 col-md-12 col-sm-12">
      <table class="table-light table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item|%>
            <tr>
              <td><%= order_item.item.name %></td>
              <td>¥<%= tax_price(order_item.item_id).to_s(:delimited) %></td>
              <td><%= order_item.quantity %></td>
              <td>¥<%= order_items_sub_price(order_item.id).to_s(:delimited) %></td>
              <%= form_with model: [:admin,order_item], url: admin_order_order_item_path(@order, order_item), method: :patch, local:true do |f| %>
                <td>
                  <%= f.select :make_status, OrderItem.make_statuses.keys %>
                </td>
                <td>
                  <%= f.submit '更新', class: "btn btn-sm btn-success" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div>
        <table class="table-light table table-borderless">
          <thead class="thead-light">
            <tr>
              <th>商品合計</th>
              <td>¥<%= (@order.total_price - postage).to_s(:delimited) %></td>
            </tr>
            <tr>
              <th>送料</th>
              <td>¥<%= postage %></td>
            </tr>
            <tr>
              <th>請求金額合計</th>
              <td>¥<%= @order.total_price.to_s(:delimited) %></td>
            </tr>
          </thead>
        </table>
    </div>
  </div>
</div>