config/routes.rb
Rails.application.routes.draw do
  devise_for :admin
  devise_for :customers

  namespace :admin do
    root to: 'homes#top'
    resources :customers, only: [:index, :show, :edit, :update]

    resources :genres, only: [:index, :create, :edit, :update]

    resources :items, only: [:index, :show, :new, :create, :edit, :update]

    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end

  end

  scope module: :public do
    root to: 'homes#top'
    get "about" => "homes#about"

    resources :items, only: [:index, :show]

    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy ]
    delete 'cart_items/:id' => 'cart_products#destroy', as: 'destroy_cart_item'

    resources :orders, only: [:index, :show, :create, :new] do
      collection do
        post :confirm
        get :complete
      end
    end

    resources :addresses, only: [:index, :create, :destroy, :edit, :update]

    resources :customers, only: [:show, :edit, :update] do
      member do
        get :quit_confirm
        patch :quit
      end
    end

  end
end

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg">
    <div class="container">
      <div class="navbar-brand logo">
        <%= link_to root_path do %>
        <%= image_tag 'logo-removebg-preview.png', size:100; %>
        <% end %>
      </div>
      <ul class="navbar-nav ml-auto">
        <% if customer_signed_in? %>

          <!--カスタマーがログインしている時 -->
          <li class="nav-item mr-5 pt-2">
            ようこそ！<span class="text-success mr-1"><%= current_customer.last_name %><%= current_customer.first_name %></span>さん！！
          </li>
          <li class="nav-item"><%= link_to " マイページ", customer_path(current_customer), class: 'btn btn-light btn-ms nav-link fas fa-house-user' %></li>
          <li class="nav-item ml-1"><%= link_to " 商品一覧", items_path, class: 'btn btn-light btn-ms nav-link fas fa-cheese' %></li>
          <li class="nav-item ml-1"><%= link_to " カート", cart_items_path, class: 'btn btn-light btn-ms nav-link fas fa-cart-plus' %></li>
          <li class="nav-item ml-1"><%= link_to " ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-light btn-ms nav-link fas fa-sign-out-alt' %></li>

        <% elsif admin_signed_in? %>

          <!-- 管理者がログインしている時 -->

          <li class="nav-item mr-5 pt-2">管理者としてログイン中</li>
          <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: 'btn btn-light btn-ms nav-link fas fa-cheese' %></li>
          <li class="nav-item ml-1"><%= link_to "会員一覧", admin_customers_path, class: 'btn btn-light btn-ms nav-link fas fa-users' %></li>
          <li class="nav-item ml-1"><%= link_to "注文履歴一覧", admin_root_path , class: 'btn btn-light btn-ms nav-link fas fa-history' %></li>
          <li class="nav-item ml-1"><%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-light btn-ms nav-link fas fa-list-alt' %></li>
          <li class="nav-item ml-1"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-light btn-ms nav-link fas fa-sign-out-alt' %></li>


        <% else %>

          <!-- ログインしていない時 -->
          <li class="nav-item mr-5 pt-2">
            ようこそ、<span class="text-success mr-1">ゲスト</span>さん！
          </li>
          <li class="nav-item"><%= link_to " About", about_path, class: 'btn btn-light btn-ms nav-link fas fa-house-user' %></li>
          <li class="nav-item ml-1"><%= link_to " 商品一覧", items_path, class: 'btn btn-light btn-ms nav-link fas fa-cheese' %></li>
          <li class="nav-item ml-1"><%= link_to " 新規登録", new_customer_registration_path, class: 'btn btn-light btn-ms nav-link fas fa-user-plus' %></li>
          <li class="nav-item ml-1"><%= link_to " ログイン", new_customer_session_path, class: 'btn btn-light btn-ms nav-link fas fa-sign-in-alt' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yusei+Magic&display=swap" rel="stylesheet">
  </head>

  <body>
    <% if current_page?(root_path) %>
      <div id="splash">
      <div id="splash_logo2"><%= image_tag 'top.jpeg', class: "d-block w-100 " %> </div>
      <div id="splash_logo"><%= image_tag 'logo.png', class: "d-block w-100 fadeUp"%></div>
      </div>
    <% end %>

    <%= render "layouts/header" %>

    <%= yield %>
  </body>
</html>